### ISSUE TITLE
`fetch_overfeat_weights_and_biases` 404 error

### ISSUE THREAD

**Issue by AdamSpannbauer** [sklearn-theano/sklearn-theano#108]
The zip of overfeat weights to be downloaded in [`fetch_overfeat_weights_and_biases`](https://github.com/sklearn-theano/sklearn-theano/blob/master/sklearn_theano/feature_extraction/overfeat.py#L61) seems to have an invalid link.  I get a 404 when running the function & when trying to navigate to the link manually.

Is there a separate location to get the weights now?

(url in function: https://dl.dropboxusercontent.com/u/15378192/net_weights.zip)

**Comment by jrosebr1** [comment]
I can validate this is true as well. #105 is relevant as well.

**Comment by kastnerkyle** [comment]
Dropbox must have changed folder sharing settings: this link should work https://www.dropbox.com/s/9brp4f5spheybwo/net_weights.zip?dl=0 .

However, given recent ecosystem changes, this project isn't really maintained any more (Theano is end-of-life, and PyTorch/TF have similar functionality to this package). I plan to write something in the README about this soon - but for now here are the weights, have fun!

**Comment by jrosebr1** [comment]
Thanks Kyle!

**Comment by kastnerkyle** [comment]
Of course, I still hope to fix the fetcher/dropbox issue since Theano isn't dead just yet :) Will see about doing that in the upcoming week.
