### ISSUE TITLE
Error in plot_asirra_example

### ISSUE THREAD

**Issue by kastnerkyle** [sklearn-theano/sklearn-theano#34]
The example code 'plot_asirra_dataset.py', gets the following error:
```
Traceback (most recent call last):
  File "plot_asirra_dataset.py", line 28, in <module>
    X, y, train_size=.6, random_state=1999)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py", line 1556, in train_test_split
    arrays = check_arrays(*arrays, **options)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 287, in check_arrays
    array.ndim)
ValueError: Found array with dim 4. Expected <= 2
```

**Comment by felixlaumon** [comment]
I got another error today when running `examples/plot_asirra_dataset.py`:

````
ValueError: The number of classes has to be greater than one.
```

Looks like that's because `np.unique(data['target'])` is `array([0.])` when `image_count` is small.

**Comment by kastnerkyle** [comment]
OK, we should put a check in the dataset to avoid that. PR is welcome if you have the time!

**Comment by kastnerkyle** [comment]
The latest commit should fix this. Try going to '~/sklearn_theano_data' and
removing the 'asirra/' directory - this should prompt a redownload of
asirra, which will take a while, but from what I could find this error is
the result of a failed download. We should probably get some kind of
checksum checking here.
