### ISSUE TITLE
ENH Decouple Protobuf requirement and extend sklearn_theano.feature_extraction.caffe

### ISSUE THREAD

**Issue by erfannoury** [sklearn-theano/sklearn-theano#45]
This issue is created based on discussion in #44.
There are two objectives that are to be accomplished.
-  [x] Removing the dependency of existing code on protobuf. 
-  [ ] Extend current sample code to include VGG_CNN_S caffemodel converted to theano.

### Protobuf
There are two main parts of the code that depend on protobuf.
The first part is [here](https://github.com/sklearn-theano/sklearn-theano/blob/master/sklearn_theano/feature_extraction/caffe/caffemodel.py#L154:L158), where `caffe_pb2` is loaded so that layer information can be extracted from it. As discussed in the aforementioned PR (#44), this here is the suggested procedure:
>This can be done by writing a function called  `_get_caffe_layer_names `, which returns a  `dict`  indexing layer names to their protobuffer keys and vice versa (as it is done in the code). This function should first look locally for a json file in which this information is coded. If the json file is not present, it should use the  `caffe_pb2`  to create it. In this case it will run into the  `try/except`  case you coded. Implementing this would make  `_parse_caffe_model`  independent from  `caffe_pb2`. 

The second part is [here](https://github.com/sklearn-theano/sklearn-theano/blob/master/sklearn_theano/feature_extraction/caffe/caffemodel.py#L89:L96), where protobuf is used for parsing the binary content of a `caffemodel` file. Thus, to be able to remove the dependency on protobuf, a parser for `caffemodel` files should be written.

### VGG_CNN_S
Another idea is to add this particular model to sklearn-theano. The parser for this new model will be based on what is currently implemented for GoogLeNet, but it might need some modifications and generalizations.

**Comment by eickenberg** [comment]
Thanks for posting the issue.

Regarding the second part of the protobuf removal you mention:

> The second part is here, where protobuf is used for parsing the binary content of a caffemodel file. > Thus, to be able to remove the dependency on protobuf, a parser for caffemodel files should be 
> written.

I'm not sure this is an easy task. The .caffemodel files are saved according to the specifications stored in `caffe.proto`, which you would either have to hardcode or parse. Don't you think this might be a lot of work? I don't think a dependency on `python-protobuf` is too bad, if `python-protobuf` is pip installable, which I think it is.

What would be more interesting in my opinion would be to try to remove the dependency on the protobuf-compiler `protoc` which is used to compile `caffe.proto` into `caffe_pb2.py`. If this compilation can be done using `python-protobuf`, that would be pretty awesome actually (I haven't check to see).

The dependency on python-protobuf can be rendered weak by storing python-pickled parsed caffemodels (parsed with `_parse_caffe_model`) somewhere online. That was our original idea, but we are not sure how this plays out with the licenses of these models, so we didn't go further in that direction.

cc @kastnerkyle

**Comment by kastnerkyle** [comment]
I think storing online and downloading is an easy path, and license thing
will not be resolved anytime soon. As long as we are open about our
attributions I think it will be OK - we are not claiming to have written
the nets, only to be providing wrappers and download tools for them. Since
the models are already online, just in an alternate format I do not forsee
serious issues with this.

A weak depend on python-protobuf would work, or we can even add it as a
submodule/static code in the repo itself, depending on size/license of
protobuf code and complexity of install. But if it is pip installable and
pure python seems reasonable to have a soft depend if you want to use caffe
models.

**Comment by erfannoury** [comment]
Sorry for late reply; I had an exam.
I agree. Parsing `.caffemodel` files without protobuf is not a trivial task. We should better remove dependency on `protoc`. `python-protobuf` is `pip`-installable. However, I don't know if protobuf files can be compiled using `python-protobuf` alone. The documentation states that:
>The complete package includes the C++ source code, which includes the
Protocol Compiler (protoc).  If you downloaded this package from PyPI
or some other Python-specific source, you may have received only the
Python part of the code.  In this case, you will need to obtain the
Protocol Compiler from some other source before you can use this
package.

So I think compiling protobuf files using solely `python-protobuf` is not possible.
But instead, we can provide compiled and pickled versions of protobuf files and have the code call into the `protoc` only when these files are not found.

**Comment by kastnerkyle** [comment]
Pickle files may not be the best way to store them. If we store as pure JSON after parsing by protoc, couldn't we just have them in the repo itself? I am working on this in preparation for a talk on Friday

**Comment by eickenberg** [comment]
They contain binary arrays, they are fully pretrained models. I guess the
BSON format could handle it, but that would be yet another dependency.
Right now, if I am not mistaken, the googlenet transformer draws on a
`joblib.dump` of the weights if it finds it. Otherwise it parses the
.caffemodel file.

Thanks Erfan for the proposition, on my phone right now, will answer better
later.

**Comment by kastnerkyle** [comment]
Looking at caffe it seems like they are using only the python interface
once the caffe_pb2 file is made. Where does protoc come into play?

**Comment by eickenberg** [comment]
Only to compile caffe.proto into caffe_pb2.py

I was hoping to be able to avoid using protoc here, but according to Erfan
this is not possible.

We can indeed upload the compiled caffe_pb2.py somewhere for the case that
protoc isn't present.

I wanted to figure out to what extent caffe_pb2.py is standalone by trying
to import it on an ec2 instance without protoc and python-protobuf

Btw, the fastest way to delve back into the codebase is probably to
download that .caffemodel file from
http://www.robots.ox.ac.uk/%7Evgg/software/deep_eval/releases/bvlc/VGG_CNN_S.caffemodel

and running it through
sklearn.feature_extraction.caffemodel._parse_caffe_model and
sklearn.feature_extraction.caffemodel.parse_caffe_model and see what
happens ;)

**Comment by kastnerkyle** [comment]
Could we require that each caffe model store it's own caffe_pb2.py and
mynet_pb2.py file? Then we would never need protoc and would be guaranteed
that the caffe_pb2.py is compatible with the model.The only people who
would need protoc then would be developers who are trying to add new caffe
models

It would also avoid problems where two models need different caffe.proto
files due to version changes or whatever

**Comment by kastnerkyle** [comment]
Though I guess this would still require python-protobuf it would be a
little cleaner than storing the weights in order given the known shape info
though I am actually OK with that too as long as it makes sense to do
Googlenet in the same way. The Inception layer would need some kind of
ordering assumption.

**Comment by kastnerkyle** [comment]
Since python-protobuf is New BSD licensed, we could also just include a
copy in utils/extern or something (kinda like six is handled in sklearn).
This way, we can do serialization without pickle and control versioning
independently from pip.

**Comment by erfannoury** [comment]
>Could we require that each caffe model store it's own caffe_pb2.py and
mynet_pb2.py file?
As you can see in #44, proto files eventually change over time for each model. Thus developer must keep the provided net_pb2.py file updated with the latest proto file.

> ... see what happens ;)
This is what happened:
```
Traceback (most recent call last):
  File "test_googlenet.py", line 46, in <module>
    test_googlenet_classifier()
  File "test_googlenet.py", line 34, in test_googlenet_classifier
    c = GoogLeNetClassifier()
  File "E:\Code Vault\Github\sklearn-theano.old\sklearn_theano\feature_extraction\caffe - Copy\googlenet.py", line 220, in __init__
    self.transform_function = _custom_get_fprop(('loss3/loss3',))
  File "E:\Code Vault\Github\sklearn-theano.old\sklearn_theano\feature_extraction\caffe - Copy\googlenet.py", line 112, in _custom_get_fprop
    model = _parse_caffe_model(protobuf_file)
  File "E:\Code Vault\Github\sklearn-theano.old\sklearn_theano\feature_extraction\caffe - Copy\caffemodel.py", line 178, in _parse_caffe_model
    specifics = LAYER_PROPERTIES[ltype]
KeyError: 'SOFTMAX'
```
Thus I added this line to `LAYER_PROPERTIES`:
```
SOFTMAX=None
```
And then I got this error:
```
Traceback (most recent call last):
  File "test_googlenet.py", line 46, in <module>
    test_googlenet_classifier()
  File "test_googlenet.py", line 34, in test_googlenet_classifier
    c = GoogLeNetClassifier()
  File "E:\Code Vault\Github\sklearn-theano.old\sklearn_theano\feature_extraction\caffe - Copy\googlenet.py", line 220, in __init__
    self.transform_function = _custom_get_fprop(('loss3/loss3',))
  File "E:\Code Vault\Github\sklearn-theano.old\sklearn_theano\feature_extraction\caffe - Copy\googlenet.py", line 117, in _custom_get_fprop
    verbose=verbose)
  File "E:\Code Vault\Github\sklearn-theano.old\sklearn_theano\feature_extraction\caffe - Copy\googlenet.py", line 90, in create_theano_expressions
    layers, blobs, inputs = parse_caffe_model(model, verbose=verbose)
  File "E:\Code Vault\Github\sklearn-theano.old\sklearn_theano\feature_extraction\caffe - Copy\caffemodel.py", line 244, in parse_caffe_model
    convolution_input = blobs[bottom_blobs[0]]
KeyError: u'data'
```
This is a WIP, so will report anything that happens.

**Comment by kastnerkyle** [comment]
The proto files only change if caffe changes, right? So if we kept the py
files fixed and stored a copy of the model we would basically be keeping a
kind of snapshot of caffe AND the model itself? We definitely want to avoid
needing to keep updated with caffe if possible...

**Comment by erfannoury** [comment]
Yes, this is a possible solution.

**Comment by kastnerkyle** [comment]
I think it would be good to split this into 2 parts. 

Part 1:
Add ```caffe_pb2.py``` to the repo under a new folder ```models/bvlc_googlenet```, and add ```python-protobuf``` in a new directory ```externals/``` . Finally, add a copy of the ```bvlc_googlenet.caffemodel``` to the Dropbox we have been using as a download storage. This way we effectively have all 3 of the "moving parts" from caffe isolated. The only issue I see is if python-protobuf doesn't maintain compatibility, at some point down the road new ```caffe_pb2.py``` files when we add models won't parse right. I would vote to cross that bridge when we get to it, which may be soon looking at the error above

Part 2:
Add a new model like VGGNet or CIFAR10-NiN by making a new directrory in ```models/```, adding a new generated ```caffe_pb2.py```, and parsing using the python-protobuf in ```externals/```. Then I can add the corresponding caffemodel to the Dropbox repo and we can ensure that the caffemodel parses correctly.

I can do part 1 tonight, and then we can test it by trying to add VGGNet which uses the ```externals/python-protobuf```. What do you think @erfannoury @eickenberg?

**Comment by erfannoury** [comment]
It's a good idea it think. And I will be working on the second part.
I only have one minor question. I suppose that protobuf file for each network should be different. But I can't find other `.proto` files. There are only `.prototxt` files associated with each model. Am I missing something?

**Comment by eickenberg** [comment]
Agreed, these are two different projects. Shipping `caffe_pb2.py` with the repo would be the first obvious step to make this work better. It would also avoid the whole rather brittle fetcher that I wrote to get it fresh from github. In hindsight that wasn't a good idea.

Putting one `caffe_pb2.py` with each model is the next step if different versions of it are necessary for different models. With the unique model we have at the moment, these two situations are equivalent, but they will cease to be once we get a new model that needs a different caffe_pb2.py. I guess this will happen, so we can already put them in specfic model folders.

Part 2 sounds like a fun undertaking :)

@erfannoury wrt to your error report, what exactly am I looking at? I see `test_googlenet`. What exactly made this fail? Did you use the other caffemodel (VGG) instead of the googlenet one? Can you try parsing directly using `_parse_caffe_model`?

Before I forget: Part 3 will be to not rewrite the class enveloping each estimator again and again. There has got to be a ton of code one can share. (For another issue)

**Comment by eickenberg** [comment]
@erfannoury there is only one (or very few) `.proto` file. This is the spec sheat for the protocol buffer. The `.prototxt` files are written according to the `caffe.proto` model and define the networks. The `.caffemodel` files are binary prototxt files which already contain the weights, whereas the `.prototxt` files are human-readable and untrained.

**Comment by eickenberg** [comment]
> And I will be working on the second part.

That would be a great help!

**Comment by kastnerkyle** [comment]
I will work up a PR for part 1 ASAP. As for the previous comment from
@erfannoury as I understand it, the prototxt model is all that is needed to
befine the architecture as long as the .proto file is the right version. If
.proto updates, you sometimes have to hack .prototxt to use the right
nomenclature

aka

what @eickenberg said

**Comment by erfannoury** [comment]
> @erfannoury wrt to your error report, what exactly am I looking at? I see  `test_googlenet` . What exactly made this fail? Did you use the other caffemodel (VGG) instead of the googlenet one? Can you try parsing directly using  `_parse_caffe_model` ?

As you suggested earlier, I replaced the `bvlc_googlenet.caffemodel` with `VGG_CNN_S.caffemodel` to see how will it go. First error was solved by adding a `SOFTMAX` layer to `LAYER_PROPERTIES` dictionary structure. But the second is encountered because the first layer listed in the `prototxt` file is apparently the first conv layer (`conv1`) before the `data` layer. It looks like the first `data` layer is not defined in the model definition file.

**Comment by erfannoury** [comment]
Yes, `VGG_CNN_S.caffemodel` has no `DATA` layer defined. But GoogLeNet has data and label layers defined. I am downloading other models to see whether they have a data layer or not.

**Comment by eickenberg** [comment]
Ah, yes, this is indeed possible. Probably importing a new network will imply some work at the input/output ends to get the parser started. Then hopefully it should run through, unless it doesn't know some of the layers yet that are employed in the new net.

Thanks for uncovering this!

**Comment by erfannoury** [comment]
Yes I suppose input/output layers should be added manually. I am currently working on it. Only have to get a bit more familiar with the contents of the `.caffemodel` file.

**Comment by kastnerkyle** [comment]
#46 removes the need for python-protobuf entirely, and adds the caffe_pb2 file specific to the version of Googlenet we have stored in the Dropbox repo. I hope we can do the same with our other supported caffe models, though maybe in time we will find a better solution for support of arbitrary stored models. For now, this seems like a good path for adding the "core" caffe models like VGGNet, etc. I am planning to do some additional documentation work showcasing Googlenet and a rough "how to" for adding new caffe models before I forget :)

It would also be amazing to make a nightly docbuild but I am not sure what machines I have available for this job. To be continued, I suppose.

**Comment by erfannoury** [comment]
So now to use a trained model from caffe, only corresponding '.caffemodel' file is needed. All other dependencies are contained. It is great. Now only new models are to be added.
________________________________

**Comment by kastnerkyle** [comment]
I just merged #46 . Tests pass from scratch repo with no saved data/models on GoogLeNet. @erfannoury You will likely need to modify caffemodel.py to look at the "right" caffe_pb2.py file - currently the it is a hardcoded import. It should probably be an argument to ```_parse_caffe_model``` or more specifically (I think) ```_open_caffe_model_file``` but you can see what works for you when working on VGGNet. The only other change should be modifying the caffe_pb2.py file you use for VGGNet to have relative imports, you can see how this was done in ```models/bvlc_googlenet/caffe_pb2.py```. There is also some dead code to be removed from ```caffemodel.py``` but I wanted to be sure everything works before changing more logic.

**Comment by eickenberg** [comment]
Thanks for the effort!

**Comment by erfannoury** [comment]
Thank you @kastnerkyle and @eickenberg.
I will modify them according to the latest changes.

I have a question. How can I know if a model's output is correct? Is there any easy way to see that weights are correctly imported from the `.caffemodel` file?

**Comment by kastnerkyle** [comment]
The best way to check is compare the outputs against outputs from Caffe
using pycaffe or something. @eickenberg has more detail here

**Comment by eickenberg** [comment]
for googlenet i took an image, output all layer outputs of the pycaffe
model to a file and then worked my way through the theano model checking
equality at each layer.

**Comment by eickenberg** [comment]
@erfannoury btw if trying to avoid the caffe install was your reason to look at sklearn-theano, then what I said above must have seemed unfair ;) -- If necessary, I can generate all the layer outputs for e.g. `skimage.data.coffee` using pycaffe for you, but it will have to wait until this weekend.

**Comment by erfannoury** [comment]
@eickenberg Yep, that's right. I haven't yet managed to successfully install Caffe. Thus I will need help testing the implementations.
P.S: Sorry for (very) late reply. I was on a trip and couldn't work on this. I am resuming my work today.

**Comment by eickenberg** [comment]
I am having trouble myself finding the right caffe version with which to load this particular model. The gist is not clear about that. When I try `clf = caffe.classifier.Classifier("./VGG_CNN_S_deploy.prototxt", "./VGG_CNN_S.caffemodel")`, I get

```
libprotobuf ERROR google/protobuf/text_format.cc:172] Error parsing text-format caffe.NetParameter: 33:6: Message type "caffe.LRNParameter" has no field named "k".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0315 10:16:21.863013  7637 upgrade_proto.cpp:623] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: ./VGG_CNN_S_deploy.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)
```

So it is using a parameter that doesn't seem to exist in my caffe version. @kastnerkyle do you have caffe installed and could give this a shot? The model is [here](https://gist.github.com/ksimonyan/fd8800eeb36e276cd6f9)

**Comment by erfannoury** [comment]
I am currently working on `VGG_CNN_S.caffemodel` and also `VGG_ILSVRC_19_layers.caffemodel`.
I only have problem using the transform function. I get this error, I think I need some help.
```ipython
Traceback (most recent call last):
  File "test_parse_caffe_model.py", line 391, in <module>
    v.transform(co)
  File "test_parse_caffe_model.py", line 357, in transform
    *self.transpose_order))[0].reshape((len(X), -1))
  File "C:\Anaconda\lib\site-packages\theano-0.6.0-py2.7.egg\theano\compile\function_module.py", line 606, in __call__
    storage_map=self.fn.storage_map)
  File "C:\Anaconda\lib\site-packages\theano-0.6.0-py2.7.egg\theano\compile\function_module.py", line 595, in __call__
    outputs = self.fn()
ValueError: GpuCorrMM images and kernel must have the same stack size

Apply node that caused the error: GpuCorrMM{valid, (1, 1)}(GpuContiguous.0, GpuContiguous.0)
Inputs types: [CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D)]
Inputs shapes: [(1, 512, 6, 6), (4096, 18432, 1, 1)]
Inputs strides: [(0, 36, 6, 1), (18432, 1, 0, 0)]
Inputs values: ['not shown', 'not shown']
```

**Comment by eickenberg** [comment]
Could you switch your theano backend to CPU and see if the error is still there? If it is, then what the caffemodel does is not perfectly replicated by the corresponding theano layer.

**Comment by erfannoury** [comment]
I switched to CPU and this is what I got:
```
Traceback (most recent call last):
  File "test_parse_caffe_model.py", line 388, in <module>
    v.transform(co)
  File "test_parse_caffe_model.py", line 357, in transform
    *self.transpose_order))[0].reshape((len(X), -1))
  File "C:\Anaconda\lib\site-packages\theano-0.6.0-py2.7.egg\theano\compile\function_module.py", line 606, in __call__
    storage_map=self.fn.storage_map)
  File "C:\Anaconda\lib\site-packages\theano-0.6.0-py2.7.egg\theano\compile\function_module.py", line 595, in __call__
    outputs = self.fn()
ValueError: the filter stack size (18432) and image stack size (512) differ
Apply node that caused the error: ConvOp{('imshp', (None, None, None)),('kshp', (None, None)),('nkern', None),('bsize', None),('dx', 1),('dy', 1),('out_mode', 'valid'),('unroll_batch', None),('unroll_kern', None),('unroll_patch', True),('imshp_logical', (None, None, None)),('kshp_logical', (None, None)),('kshp_logical_top_aligned', True)}(Subtensor{::, ::, int64:int64:, int64:int64:}.0, <TensorType(float32, 4D)>)
Inputs types: [TensorType(float32, 4D), TensorType(float32, 4D)]
Inputs shapes: [(1L, 512L, 6L, 6L), (4096L, 18432L, 1L, 1L)]
Inputs strides: [(73728L, 144L, 24L, 4L), (73728L, 4L, 301989888L, 301989888L)]
Inputs values: ['not shown', 'not shown']
```
I think some size mismatches are causing the problem. Specifically, I don't exactly understand what `transpose_order` is?

**Comment by eickenberg** [comment]
Can you use `parse_caffe_model` to extract all theano expressions
separately and work with those? It looks like you are trying to make this
work globally at once, but there are probably things to be taken care of at
each layer, starting with the first. So use `parse_caffe_model` to obtain
the theano expressions (they should be in the `blobs` output if there is
one with that name). And then you take the first one and compile it against
the input. If you can pass an image through, perfect, move on to the
second. And so on. You can also try to identify the layer on which it is
not working by dichotomy, of course.

**Comment by kastnerkyle** [comment]
This kind of layerwise stepping is the thing we have had to do with all
other models so far :) Maybe if we get really into this we can automate at
some point, but for now it is manual work. Does this make sense?

**Comment by erfannoury** [comment]
Yes, it makes sense I have been trying out your suggestion. I hope it will help me find the problem and finally I can implement VGG caffemodels, too.
BTW, I have a question. In the GoogLeNet caffe model, there is a description of a mean image. I think this image should be subtracted from the input before passing in the input image. Have you taken care of this issue?

**Comment by erfannoury** [comment]
This is how I tried to perform layer-wise data transformation, and the output I got:
https://gist.github.com/erfannoury/c3cf818e9bae410922b9

As you can see, size mismatch happens when output from `pool1` is passed into `conv2`. I am still confused by the `transpose_order` that you pass to the `transpose` function.

**Comment by eickenberg** [comment]
transpose_order was introduced to reorder axes to make them compatible with
typical nnet convolutions. an rgb image is (h,w,c) where c=3 color
channels. input to network must be (n, c, h, w), where n is num images. the
transpose is done one single time at the beginning as preprocessing. in
your gist, it is applied at every layer, moving the axes around in an
uncontrolled way. suggestion: prepare your input image by calling transpose
on it outside your function. don't use transpose inside your function.

**Comment by erfannoury** [comment]
I corrected the implementation and I have updated the gist (https://gist.github.com/erfannoury/c3cf818e9bae410922b9). 
Now problem occurs at `pool5` to `fc6`.

**Comment by eickenberg** [comment]
You have hit a reshaping issue at the border between a convolutional layer
and a fully connected layer:

512 * 6 * 6 = 18432

The output of the conv layer is still in (channel x height x width) shape
and the fully connected layer wants this input ravelled.

In googlenet I reformulated all fully connected layers as convolutions, in
order to be able to do sliding window detection. I propose to do this here,
to:

reshape the blob of shape

(4096, 18432, 1, 1) into (4096, 512, 6, 6)

and use a convolution layer instead of a simple dot product.


(the alternative would have been to reshape the previous output from
(n, 512, 6, 6) to (n, 18432))


Does this help?

**Comment by eickenberg** [comment]
Congrats btw, this is progress!!

**Comment by erfannoury** [comment]
Ok, thanks to your suggestions, layer-wise transformation works. You can see the final gist and the output [here](https://gist.github.com/erfannoury/c3cf818e9bae410922b9).

**Comment by erfannoury** [comment]
I submitted the pull request (https://github.com/sklearn-theano/sklearn-theano/pull/50).
It would be great if you could compare the predictions against the pycaffe.

**Comment by kastnerkyle** [comment]
Sorry we let this stagnate. I will try and look at it in the next few weeks. I managed to fix some py2 / py3 issues with the googlenet code (I think) in #76 so I hope that we can use those same fixes for the VGG wrapper

**Comment by kastnerkyle** [comment]
I think #92 handles this
