### ISSUE TITLE
OverfeatTransformer's transform should use minibatch iteration for fprop

### ISSUE THREAD

**Issue by felixlaumon** [sklearn-theano/sklearn-theano#47]
OverfeatTransformer's transform causes an out-of-memory error (from theano) when performing on a non-trivial dataset.

**Comment by eickenberg** [comment]
You are totally right. Thanks for pointing this out - introducing batches
will make the transformer much more usable! We had intended this behavior
originally and I cannot remember what sidetracked us away from it. I should
be able to take care of this at the weekend.

Thanks again, this is very helpful feedback.

**Comment by felixlaumon** [comment]
Awesome! BTW, the documentation should mention that cuDNN is a required dependency.

**Comment by jrosebr1** [comment]
Being able to batch transforms inside of OverfeatTransform would be awesome! In the past I've simply created a "make_batch" function that takes a set of image paths and labels and loads them into Bunch, which I then pass on to OverfeatTransform. It's pretty simple to do, although for convenience batch transforms would be a great addition!

**Comment by kastnerkyle** [comment]
@felixlaumon cuDNN should not be a required dependency. It should be optional, and theano should handle deciding when to use it. I don't even have it installed! 

Do you have an example that failed because of cuDNN?

**Comment by felixlaumon** [comment]
Actually I think it's just because I was using the bleeding edge version of Theano. Works fine on 0.6

**Comment by kastnerkyle** [comment]
This should be fixed for both GoogLeNet and Overfeat now!
