### ISSUE TITLE
pip install doesn't include .jpg images?

### ISSUE THREAD

**Issue by kastnerkyle** [sklearn-theano/sklearn-theano#51]
Installing with
```
pip install git+https://github.com/sklearn-theano/sklearn-theano
```
seems to break the localization tutorial. Still investigating...

**Comment by kastnerkyle** [comment]
#52 still didn't fix it. Need to find a way to force pip to include the .jpg samples. For now, I will just put the image in my presentation folder for PyCon and change the path. But this should get fixed next week during the sprints

**Comment by kastnerkyle** [comment]
Adding the MANIFEST.in file appears to have fixed the issue

**Comment by kastnerkyle** [comment]
Still not working... I will continue trying to fix.

**Comment by kastnerkyle** [comment]
#57 and #54 together managed to get the job done. See http://stackoverflow.com/questions/7522250/how-to-include-package-data-with-setuptools-distribute for more information on the problem.

**Comment by eickenberg** [comment]
thanks for the effort! that wasn't trivial
