### ISSUE TITLE
Would it be possible to get it via a 'wheel' package on Pypi ?

### ISSUE THREAD

**Issue by stonebig** [sklearn-theano/sklearn-theano#62]
otherwise a pip update will find nothing, or something else.
Need = an universal wheel, or at least a wheel  for Python3.4+ Windows 32/64 bit, or at worst a page with no download available

**Comment by kastnerkyle** [comment]
We are not quite ready for a pip release yet or proper download beyond github, but when it comes we fully plan to support Python 3.4 and Windows should work without issue unless I am missing something.

**Comment by stonebig** [comment]
ok, will wait.

**Comment by kastnerkyle** [comment]
Once we have a release, this will happen. Ideally we can automate a big piece of this - closing for now.
