### ISSUE TITLE
pixel wise features

### ISSUE THREAD

**Issue by atemysemicolon** [sklearn-theano/sklearn-theano#64]
I would like to see if I can use CNN to obtain rich or semi-rich pixel wise features for later classifying (using an SVM or so) into (as of now) unknown target classes. I think the last few layers of the network make it dataset-specific, right? Can I use sklearn-theano to remove some layers, perhaps for speed and to tackle dataset variance? I couldn't quite understand it from the documentation and couldn't find a forum. Sorry if it's the wrong place, I am new to CNN.

**Comment by erfannoury** [comment]
You can use CNNs to obtain (semi-)rich pixel-wise features. You only have to note that fully connected layers (usually last few layers of the network) don't have localization information and thus aren't useful for pixel-wise features. CNNs consist of multiple consecutive convolutional layers connected to multiple consecutive fully connected layers (this is not a general description).
The trick widely used is to obtain network activations for all convolutional layers, resize (or interpolate) each layer to the size of input image, stack layers on top of each other and then you have features for all of your pixels. You can also experiment with whatever combinations of conv layers you want.
For more formal discussion of this method see [Hypercolumns for Object Segmentation and Fine-grained Localization](http://arxiv.org/abs/1411.5752) and for an application of this method you can see this paper [Fast Bird Part Localization for Fine-Grained Categorization](http://yassersouri.github.io/papers/fgvc-2015-fast-bird-part.pdf).

[_**Disclosure**: author of the second paper and I work in the same lab_]

**Comment by atemysemicolon** [comment]
Just as a follow up, can I do this easily with scikit-learn theano ? (Basically, does scikit-theano expose the inner layers of the network?)

**Comment by eickenberg** [comment]
yes, you can get all of them by specifying which ones you want using the
keyword "output_layers=" in e.g. OverfeatTransformer

**Comment by atemysemicolon** [comment]
Thanks!
