### ISSUE TITLE
Flag for using GPU

### ISSUE THREAD

**Issue by atemysemicolon** [sklearn-theano/sklearn-theano#67]
Hello, 
I use ubuntu and haven't installed CUDA sdk yet on my system. Scikit-theano has installed well and it runs(rather slowly). Once I install CUDA (and the GPU drivers, etc.) , can I force scikit-theano to use my GPU over my CPU? 

Cheers,
The semicolon guy

**Comment by kastnerkyle** [comment]
Use THEANO_FLAGS="mode=gpu, floatX=float32". For example:
```
THEANO_FLAGS="mode=gpu, floatX=float32" python plot_classification.py
```
 See the Theano documentation for more details here: 
http://deeplearning.net/software/theano/
