### ISSUE TITLE
Caffe models do not work in Python 3

### ISSUE THREAD

**Issue by kastnerkyle** [sklearn-theano/sklearn-theano#70]
This is a non-trivial issue, but one I am working on tackling now. The issue lies in protobuf from what I can see, and it may require having 2 versions in externals/ - one for python 2.x and one for python 3.x . Caffe does not (to my knowledge) use or support protobuf3, so the changes made will not be the same as bringing in protobuf3 and compiling with it.

**Comment by dwf** [comment]
Does this work yet?

**Comment by kastnerkyle** [comment]
Not yet... but it can. Was planning to work on it soon but can give
pointers to the piece that needs fixing. It boils down to python3 strings
and this line:
https://github.com/sklearn-theano/sklearn-theano/blob/master/sklearn_theano/feature_extraction/caffe/caffemodel.py#L87

I think with the right incantation of py3 strings -> ascii or latin-1
encoding, etc. binary it should work. I spent a long time doing it the
wrong way. Also there may be a few issues (that we tried in your office to
patch) with relative vs. absolute imports, etc. Worst case we can
explicitly treat as binary using struct.unpack I am reasonably sure

On Tue, Jul 7, 2015 at 1:49 PM, David Warde-Farley <notifications@github.com

**Comment by kastnerkyle** [comment]
Should be ok with #76 . We need a general import solution but that is a problem for another day :)

**Comment by kastnerkyle** [comment]
Fixed by #76

**Comment by eickenberg** [comment]
thanks for taking care of that!
