### ISSUE TITLE
running examples error

### ISSUE THREAD

**Issue by RoyalMajesty** [sklearn-theano/sklearn-theano#72]
When I try to run the examples(plot_classification.py,plot_overfeat_layer1_filters.py) I get the error:
raise BadZipfile, "File is not a zip file" in zipfile.py
Could you help me out?

**Comment by eickenberg** [comment]
Could you run `python -c "from sklearn_theano.datasets import get_dataset_dir; print get_dataset_dir('overfeat_weights')"` and look inside the directory it prints and tell me what you find?

Also, what system are you working on and which python version?

**Comment by RoyalMajesty** [comment]
It's a zip file "net_weights.zip"
I have win 8.1 and I am using Anaconda(python 2.7)

**Comment by eickenberg** [comment]
can you unzip it and put the contents in that same folder manually? Or does
that give an error, too?

**Comment by RoyalMajesty** [comment]
It gives an error : The archive is either unknown format or damaged.

**Comment by eickenberg** [comment]
Ok, then delete it and try re-running the example

**Comment by RoyalMajesty** [comment]
I think I have a problem downloading it using command prompt.Is there a link that I can download the net_weights?

**Comment by eickenberg** [comment]
Try downloading this
https://dl.dropboxusercontent.com/u/15378192/net_weights.zip manually into
the folder with the broken zip file (which you have to delete again).

Could you also give us the screen output on the failed download? Does it
print anything?

**Comment by RoyalMajesty** [comment]
Here is the screen output
![error](https://cloud.githubusercontent.com/assets/8119000/7901396/4236d77c-079a-11e5-96ca-1954a38cbea0.PNG)

**Comment by eickenberg** [comment]
Does it work now?

**Comment by RoyalMajesty** [comment]
Sorry for the delay.
Yeah it worked.Thanks

**Comment by eickenberg** [comment]
Cool!
